apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
        - name: gitops-app-cont
          image: lehardocker/gitops-app: 37592da
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
