apiVersion: apps/v1
kind: Deployment
metadata:
   name: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      name: gitops-app
      labels:
        app: gitops
    spec:
      containers:
        - name: gitops-app-cont
          image: lehardocker/gitops-app:v1.0.0
          ports:
            - containerPort: 3000




