apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sureshkumar-devops/gitops-argocd-demo
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc        
    namespace: default
  syncPolicy
    automated:
      prune: true
      selfHeal: true
